### ISSUE TITLE
我试了下报错了

### ISSUE THREAD

**Issue by netmou** [Endy-c/php-gm-crypto#1]
$config = [
    // mode string 'cbc' or 'ecb' is supported, default is 'cbc'.
    'mode'  => 'ecb',
    // password, will be processed by substr(md5($key), 0, 16)
    'key'   => '2qwEbbAaHqQeUGdZ',
    // the iv used by 'cbc' mode, will be will be processed by substr(md5($iv), 0, 16)
    'iv'    => '{replace-your-iv-here}'
];
$data = 'Csfm78m1llXzHpEWYq6lW/2CXZ2ZfIerdaLb8VHqkP3QEk/GRV5JbE9pOy1WW4qs956HoePH+YkE/wKX//v81Q==';
$sm4 = new SMEncryption($config);
$a= $sm4->sm4decrypt(base64_decode($data));
var_export($a);

**Comment by Endy-c** [comment]
你的data是用什么加密的？这个库会将key做一次substr(md5($key), 0, 16)操作，如果你使用其他方法加密，确保key也做了相同操作，否则密钥不对称，无法解出明文。

**Comment by Endy-c** [comment]
更新一下版本，新增了配置项`$config['hash']`，默认为`false`，不对key和iv做散列，与前端保持一致。
